import { useState } from 'react';
import Dropzone from '../shared/Dropzone';
import Button from '../shared/Button';
import { computeVerdict } from '../../detectors/verdictEngine';
import { MOCK_DETECTORS } from '../../detectors/mockDetectors';
import { validateCarrierFile } from '../../utils/fileValidation';
import { formatBytes } from '../../utils/formatBytes';
import { hasAppendedPayload } from '../../engines/binary/eofAppend';
import { generateForensicPdf } from '../../utils/generatePdf';
import type { VerdictResult } from '../../detectors/types';

interface ReportData {
  fileName: string;
  fileSize: number;
  fileType: string;
  analysisTimestamp: string;
  verdict: VerdictResult;
  validationNotes: string[];
  hasEofPayload: boolean;
}

function buildReportText(report: ReportData): string {
  const lines: string[] = [];
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('  STEGANALIZ v1.0 - FORENSIC ANALYSIS REPORT');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('');
  lines.push('CASE INFORMATION');
  lines.push('─────────────────────────────────────────────────────────────');
  lines.push(`File name      : ${report.fileName}`);
  lines.push(`File size      : ${formatBytes(report.fileSize)} (${report.fileSize} bytes)`);
  lines.push(`File type      : ${report.fileType}`);
  lines.push(`Analysis time  : ${report.analysisTimestamp}`);
  lines.push(`Processing     : Client-side only - no data transmitted`);
  lines.push('');
  lines.push('OVERALL VERDICT');
  lines.push('─────────────────────────────────────────────────────────────');
  lines.push(`Verdict        : ${report.verdict.overallLabel}`);
  lines.push(`Confidence     : ${report.verdict.overallScore}%`);
  lines.push(`EOF payload    : ${report.hasEofPayload ? 'DETECTED' : 'Not detected'}`);
  lines.push('');
  if (report.validationNotes.length > 0) {
    lines.push('FILE VALIDATION NOTES');
    lines.push('─────────────────────────────────────────────────────────────');
    for (const note of report.validationNotes) lines.push(`  • ${note}`);
    lines.push('');
  }
  lines.push('DETECTOR RESULTS');
  lines.push('─────────────────────────────────────────────────────────────');
  lines.push(`${'Detector'.padEnd(35)} ${'Label'.padEnd(12)} Score`);
  lines.push('─────────────────────────────────────────────────────────────');
  for (const result of report.verdict.results) {
    lines.push(
      `${result.detectorName.padEnd(35)} ${result.label.padEnd(12)} ${String(result.score + '%').padStart(5)}`
    );
    if (result.details) lines.push(`  └─ ${result.details}`);
  }
  lines.push('');
  lines.push('DISCLAIMER');
  lines.push('─────────────────────────────────────────────────────────────');
  lines.push('This report is generated by automated statistical analysis.');
  lines.push('It should not be treated as conclusive forensic evidence without');
  lines.push('independent expert verification.');
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('  Generated by Steganaliz v1.0 | steganaliz.emerc.site');
  lines.push('═══════════════════════════════════════════════════════════════');
  return lines.join('\n');
}

export default function ForensicReport() {
  const [file, setFile] = useState<File | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [report, setReport] = useState<ReportData | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleFile = (f: File) => {
    setFile(f);
    setReport(null);
    setErrorMessage(null);
  };

  const generateReport = async () => {
    if (!file) return;
    setIsGenerating(true);
    setErrorMessage(null);
    try {
      const bytes = new Uint8Array(await file.arrayBuffer());
      const verdict = await computeVerdict(file, MOCK_DETECTORS);
      const hasEof = hasAppendedPayload(bytes);

      const validationNotes: string[] = [];
      const validation = await validateCarrierFile(file);
      if (!validation.valid && validation.reason) {
        validationNotes.push(validation.reason);
      }

      const ext = file.name.split('.').pop()?.toLowerCase() ?? 'unknown';

      setReport({
        fileName: file.name,
        fileSize: file.size,
        fileType: `${ext.toUpperCase()} (${file.type || 'unknown MIME type'})`,
        analysisTimestamp: new Date()
          .toISOString()
          .replace('T', ' ')
          .replace(/\.\d+Z$/, ' UTC'),
        verdict,
        validationNotes,
        hasEofPayload: hasEof,
      });
    } catch {
      setErrorMessage('Analysis failed - check the browser console for details.');
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadTxt = () => {
    if (!report) return;
    const text = buildReportText(report);
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const safeName = report.fileName.replace(/[^a-z0-9_-]/gi, '_');
    a.href = url;
    a.download = `steganaliz_report_${safeName}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPdf = async () => {
    if (!report) return;
    setIsExportingPdf(true);
    try {
      const pdfBytes = await generateForensicPdf(report);
      // const blob = new Blob([pdfBytes], { type: 'application/pdf' });
      const blob = new Blob([pdfBytes as BlobPart], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      const safeName = report.fileName.replace(/[^a-z0-9_-]/gi, '_');
      a.href = url;
      a.download = `steganaliz_report_${safeName}_${Date.now()}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setIsExportingPdf(false);
    }
  };

  return (
    <div className="max-w-2xl space-y-5">
      <Dropzone onFileSelected={handleFile} acceptedLabel="any supported carrier format" />

      {errorMessage && <p className="text-xs text-stgDanger">{errorMessage}</p>}

      {file && (
        <Button onClick={generateReport} disabled={isGenerating}>
          {isGenerating ? 'Running analysis…' : 'Generate forensic report'}
        </Button>
      )}

      {report && (
        <>
          <div
            className={`border rounded px-4 py-2 text-sm font-medium ${
              report.verdict.overallLabel === 'STEGO'
                ? 'border-stgDanger bg-stgDanger/10 text-stgDanger'
                : report.verdict.overallLabel === 'SUSPICIOUS'
                  ? 'border-stgWarning bg-stgWarning/10 text-stgWarning'
                  : 'border-stgSuccess bg-stgSuccess/10 text-stgSuccess'
            }`}
          >
            {report.verdict.overallLabel} · {report.verdict.overallScore}% confidence
          </div>

          <pre className="mono text-xs leading-relaxed bg-stgBlack text-stgTextOnDark rounded px-4 py-4 overflow-x-auto whitespace-pre max-h-96 overflow-y-auto">
            {buildReportText(report)}
          </pre>

          <div className="flex gap-3">
            <Button variant="secondary" onClick={downloadTxt}>
              Download .txt
            </Button>
            <Button onClick={downloadPdf} disabled={isExportingPdf}>
              {isExportingPdf ? 'Generating PDF…' : 'Download PDF report'}
            </Button>
          </div>
        </>
      )}
    </div>
  );
}